settings:
  title: 'Status Page'
  url: 'https://status.kamner.de' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: kamner-de # unique identifier
    name: kamner.de
    # description: 'You write code. They handle the rest.' # default=empty
    url: 'https://kamner.de/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    # followRedirect: false # should fetch follow redirects, default=false

  - id: clickstart-cloud
    name: https://clickstart.cloud
    url: 'https://clickstart.cloud'
    method: GET
    expectStatus: 200
